"""ssh client + outbound scp (kernel/src/ssh/client.rs, cmds/ssh.rs, cmds/scp.rs).

Driven against the guest's OWN sshd over loopback — fully self-contained, no
external server. This exercises the full client handshake (curve25519 kex,
ed25519 host-key verification, password auth, channel exec) and the scp
source/sink protocol over an SSH channel. (Interop with real OpenSSH is verified
manually; the test image can't spawn a docker sshd.)
"""


def test_ssh_exec(g):
    # SSHPASS supplies the password non-interactively.
    out, err, st = g.run("SSHPASS=root ssh root@127.0.0.1 'echo REMOTE_OK; id -u'", timeout=40)
    assert "REMOTE_OK" in out, out + err
    assert "0" in out, out + err  # id -u for root


def test_ssh_stdin_forwarding(g):
    out, err, st = g.run("echo piped-in | SSHPASS=root ssh root@127.0.0.1 'cat'", timeout=40)
    assert "piped-in" in out, out + err


def test_scp_upload_loopback(g):
    g.ok("printf 'scp-out-up\\n' > /tmp/so_src.txt")
    out, err, st = g.run("SSHPASS=root scp /tmp/so_src.txt root@127.0.0.1:/tmp/so_dst.txt", timeout=40)
    assert st == 0, out + err
    assert g.ok("cat /tmp/so_dst.txt").strip() == "scp-out-up"


def test_scp_download_loopback(g):
    g.ok("printf 'scp-out-down\\n' > /tmp/sd_src.txt")
    out, err, st = g.run(
        "SSHPASS=root scp root@127.0.0.1:/tmp/sd_src.txt /tmp/sd_dst.txt && cat /tmp/sd_dst.txt",
        timeout=40,
    )
    assert st == 0, out + err
    assert "scp-out-down" in out, out + err


def test_scp_local_only_errors(g):
    # No remote side → clear error, not a silent no-op.
    out, err, st = g.run("scp /tmp/a /tmp/b", timeout=20)
    assert st != 0
    assert "remote" in (out + err).lower()


def test_ssh_known_hosts_tofu(g):
    g.run("rm -f /root/.ssh/known_hosts")
    out, err, st = g.run("SSHPASS=root ssh root@127.0.0.1 'echo hi'", timeout=40)
    assert "permanently added" in (out + err).lower(), out + err
    kh = g.ok("cat /root/.ssh/known_hosts")
    assert kh.startswith("127.0.0.1 ssh-ed25519 "), kh
    # Second connect: host known, no "permanently added".
    out2, err2, _ = g.run("SSHPASS=root ssh root@127.0.0.1 'echo hi2'", timeout=40)
    assert "permanently added" not in (out2 + err2).lower(), out2 + err2
    assert "hi2" in out2


def test_ssh_known_hosts_mismatch_refused(g):
    # A wrong stored key must abort the connection.
    bogus = "127.0.0.1 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIWRvbmd0cnVzdG1lZG9uZ3RydXN0bWVkb25ndHI=\n"
    g.ok("mkdir -p /root/.ssh", timeout=20)
    g.ok("cat > /root/.ssh/known_hosts", stdin=bogus)
    out, err, st = g.run("SSHPASS=root ssh root@127.0.0.1 'echo NOPE'", timeout=40)
    assert st != 0
    assert "mismatch" in (out + err).lower() or "man-in" in (out + err).lower(), out + err
    assert "NOPE" not in out
    g.run("rm -f /root/.ssh/known_hosts")


def test_ssh_encrypted_key_passphrase(g):
    """A passphrase-protected OpenSSH key (aes256-ctr + bcrypt) generated by real
    ssh-keygen must decrypt with the passphrase (fed to the prompt) and log in."""
    import base64 as b64mod
    import os
    import subprocess
    import tempfile

    with tempfile.TemporaryDirectory() as d:
        kp = os.path.join(d, "enc")
        subprocess.run(
            ["ssh-keygen", "-t", "ed25519", "-N", "testpass123", "-C", "enc@t", "-f", kp, "-q"],
            check=True, capture_output=True,
        )
        priv = open(kp, "rb").read()
        pub = open(kp + ".pub").read().strip()

    g.run("rm -f /root/.ssh/known_hosts /root/.ssh/authorized_keys")
    g.ok("mkdir -p /root/.ssh; base64 -d > /root/.ssh/id_ed25519 && chmod 600 /root/.ssh/id_ed25519",
         stdin=b64mod.b64encode(priv).decode())
    g.ok(f"printf '%s\\n' '{pub}' > /root/.ssh/authorized_keys")
    # Correct passphrase (piped to the prompt) → key decrypts → pubkey auth.
    out, err, st = g.run("printf 'testpass123\\n' | ssh root@127.0.0.1 'echo ENC_OK'", timeout=45)
    assert "ENC_OK" in out, out + err
    # Wrong passphrase → rejected.
    out2, err2, _ = g.run("printf 'nope\\nnope\\nnope\\n' | ssh root@127.0.0.1 'echo NO'", timeout=45)
    assert "NO" not in out2
    assert "bad passphrase" in (out2 + err2).lower(), out2 + err2
    g.run("rm -f /root/.ssh/id_ed25519 /root/.ssh/authorized_keys /root/.ssh/known_hosts")


def test_ssh_keygen_encrypted(g):
    """ssh-keygen -N generates a passphrase-encrypted key, usable via the prompt."""
    g.run("rm -f /root/.ssh/id_ed25519 /root/.ssh/id_ed25519.pub /root/.ssh/authorized_keys /root/.ssh/known_hosts")
    out = g.ok("ssh-keygen -N topsecret -C enc@fastros", timeout=30)
    assert "protected with a passphrase" in out, out
    g.ok("cat /root/.ssh/id_ed25519.pub >> /root/.ssh/authorized_keys")
    # Correct passphrase → decrypts the just-generated key → logs in.
    out2, err2, _ = g.run("printf 'topsecret\\n' | ssh root@127.0.0.1 'echo KEYGEN_ENC_OK'", timeout=45)
    assert "KEYGEN_ENC_OK" in out2, out2 + err2
    # Wrong passphrase → rejected.
    out3, err3, _ = g.run("printf 'x\\nx\\nx\\n' | ssh root@127.0.0.1 'echo NO'", timeout=45)
    assert "NO" not in out3 and "bad passphrase" in (out3 + err3).lower(), out3 + err3
    g.run("rm -f /root/.ssh/id_ed25519 /root/.ssh/authorized_keys /root/.ssh/known_hosts")


def test_ssh_keygen_and_pubkey_auth(g):
    g.run("rm -f /root/.ssh/id_ed25519 /root/.ssh/id_ed25519.pub /root/.ssh/authorized_keys /root/.ssh/known_hosts")
    out = g.ok("ssh-keygen -N ''", timeout=30)  # -N '' = no passphrase, no prompt
    assert "saved in" in out and "fingerprint" in out.lower(), out
    assert g.ok("test -f /root/.ssh/id_ed25519 && echo yes").strip() == "yes"
    g.ok("cat /root/.ssh/id_ed25519.pub >> /root/.ssh/authorized_keys")
    # No SSHPASS: must authenticate by public key.
    out2, err2, st = g.run("ssh root@127.0.0.1 'echo PUBKEY_OK; whoami'", timeout=40)
    assert "PUBKEY_OK" in out2, out2 + err2
    assert "root" in out2, out2 + err2
