[package]
name = "fastros-kernel"
description = "The FastROS kernel"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "fastros"
path = "src/main.rs"
test = false
bench = false

[dependencies]
fastros-alloc = { path = "../lib/alloc" }
fastros-codec = { path = "../lib/codec" }
fastros-ext2 = { path = "../lib/ext2" }
fastros-netfilter = { path = "../lib/netfilter" }
fastros-sh = { path = "../lib/sh" }
fastros-archive = { path = "../lib/archive" }
sha2 = { version = "0.10", default-features = false, features = ["force-soft"] }
hmac = { version = "0.12", default-features = false }
chacha20 = { version = "0.9", default-features = false }
poly1305 = { version = "0.8", default-features = false }
aes = { version = "0.8", default-features = false }
ctr = { version = "0.9", default-features = false }
x25519-dalek = { version = "2", default-features = false, features = ["static_secrets"] }
ed25519-dalek = { version = "2", default-features = false }
smoltcp = { version = "0.12", default-features = false, features = ["alloc", "medium-ethernet", "proto-ipv4", "socket-tcp", "socket-udp", "socket-icmp", "socket-dhcpv4"] }
regex = { version = "1", default-features = false, features = ["perf", "unicode"] }
argon2 ={ version = "0.5", default-features = false, features = ["alloc"] }
bcrypt-pbkdf = { version = "0.10", default-features = false, features = ["alloc"] }
